name: olist_dbt_analytics

profile: olist_dbt_analytics

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  olist_dbt_analytics:
    +static_analysis: strict
    staging:
      +materialized: view
    marts:
      +materialized: table
      analytics:
        +materialized: table