name: olist_ecommerce

profile: olist_ecommerce

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"


models:
  olist_ecommerce:
    +static_analysis: strict
    staging:
      +materialized: view
    marts:
      +materialized: table
      analytics:
        +materialized: table
